import {
  booleanSchema,
  buildArgv,
  createTool,
  integerSchema,
  pathSchema,
  stringArraySchema,
  stringSchema,
  withCommonOutput,
} from "./shared.mjs";

const authoringProperties = withCommonOutput({
  text: stringSchema("Freeform authoring text."),
  room: stringArraySchema("Room authoring specs."),
  floorTile: stringArraySchema("Floor tile specs."),
  trap: stringArraySchema("Trap specs."),
  hazard: stringArraySchema("Hazard specs."),
  resource: stringArraySchema("Resource specs."),
  delver: stringArraySchema("Delver specs."),
  warden: stringArraySchema("Warden specs."),
  goal: stringSchema("Goal text override."),
  dungeonAffinity: stringSchema("Dungeon affinity override."),
  budgetTokens: integerSchema("Hard budget cap in tokens.", { minimum: 1 }),
  dungeonBudgetTokens: integerSchema("Separate hard budget cap for dungeon-side authored objects.", { minimum: 1 }),
  delverBudgetTokens: integerSchema("Separate hard budget cap for delver-side authored objects.", { minimum: 1 }),
  budget: pathSchema("Budget artifact path."),
  priceList: pathSchema("Price list artifact path."),
  emitIntermediates: booleanSchema("Persist non-canonical sidecar artifacts."),
  dryRun: booleanSchema("Validate inputs without writing artifacts when supported."),
});

const authoringSpec = [
  { key: "text" },
  { key: "room", repeatable: true },
  { key: "floorTile", flag: "floor-tile", repeatable: true },
  { key: "trap", repeatable: true },
  { key: "hazard", repeatable: true },
  { key: "resource", repeatable: true },
  { key: "delver", repeatable: true },
  { key: "warden", repeatable: true },
  { key: "goal" },
  { key: "dungeonAffinity", flag: "dungeon-affinity" },
  { key: "budgetTokens", flag: "budget-tokens" },
  { key: "dungeonBudgetTokens", flag: "dungeon-budget-tokens" },
  { key: "delverBudgetTokens", flag: "delver-budget-tokens" },
  { key: "budget" },
  { key: "priceList", flag: "price-list" },
  { key: "emitIntermediates", flag: "emit-intermediates", boolean: true },
  { key: "outDir", flag: "out-dir" },
  { key: "runId", flag: "run-id" },
  { key: "createdAt", flag: "created-at" },
  { key: "dryRun", flag: "dry-run", boolean: true },
];

export const authoringTools = [
  createTool({
    name: "ak_create",
    description: "Create authored build artifacts from freeform and structured object specs.",
    command: "create",
    inputSchema: {
      properties: authoringProperties,
    },
    buildArgs: (args) => buildArgv(args, authoringSpec),
  }),
  createTool({
    name: "ak_configure",
    description: "Configure authored build artifacts from freeform and structured object specs.",
    command: "configure",
    inputSchema: {
      properties: authoringProperties,
    },
    buildArgs: (args) => buildArgv(args, authoringSpec.filter((entry) => entry.key !== "dryRun")),
  }),
  createTool({
    name: "ak_room_plan",
    description: "Build a room-only authoring plan.",
    command: "room-plan",
    inputSchema: {
      required: ["room"],
      properties: withCommonOutput({
        room: stringArraySchema("Room specs."),
        goal: stringSchema("Goal text override."),
        dungeonAffinity: stringSchema("Dungeon affinity override."),
        budgetTokens: integerSchema("Hard budget cap in tokens.", { minimum: 1 }),
        budget: pathSchema("Budget artifact path."),
        priceList: pathSchema("Price list artifact path."),
        emitIntermediates: booleanSchema("Persist non-canonical sidecar artifacts."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "room", repeatable: true },
      { key: "goal" },
      { key: "dungeonAffinity", flag: "dungeon-affinity" },
      { key: "budgetTokens", flag: "budget-tokens" },
      { key: "budget" },
      { key: "priceList", flag: "price-list" },
      { key: "emitIntermediates", flag: "emit-intermediates", boolean: true },
      { key: "outDir", flag: "out-dir" },
      { key: "runId", flag: "run-id" },
      { key: "createdAt", flag: "created-at" },
    ]),
  }),
  createTool({
    name: "ak_delver_plan",
    description: "Build a delver-only authoring plan.",
    command: "delver-plan",
    inputSchema: {
      required: ["delver"],
      properties: withCommonOutput({
        delver: stringArraySchema("Delver specs."),
        goal: stringSchema("Goal text override."),
        dungeonAffinity: stringSchema("Dungeon affinity override."),
        budgetTokens: integerSchema("Hard budget cap in tokens.", { minimum: 1 }),
        budget: pathSchema("Budget artifact path."),
        priceList: pathSchema("Price list artifact path."),
        emitIntermediates: booleanSchema("Persist non-canonical sidecar artifacts."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "delver", repeatable: true },
      { key: "goal" },
      { key: "dungeonAffinity", flag: "dungeon-affinity" },
      { key: "budgetTokens", flag: "budget-tokens" },
      { key: "budget" },
      { key: "priceList", flag: "price-list" },
      { key: "emitIntermediates", flag: "emit-intermediates", boolean: true },
      { key: "outDir", flag: "out-dir" },
      { key: "runId", flag: "run-id" },
      { key: "createdAt", flag: "created-at" },
    ]),
  }),
  createTool({
    name: "ak_warden_plan",
    description: "Build a warden-only authoring plan.",
    command: "warden-plan",
    inputSchema: {
      required: ["warden"],
      properties: withCommonOutput({
        warden: stringArraySchema("Warden specs."),
        goal: stringSchema("Goal text override."),
        dungeonAffinity: stringSchema("Dungeon affinity override."),
        budgetTokens: integerSchema("Hard budget cap in tokens.", { minimum: 1 }),
        budget: pathSchema("Budget artifact path."),
        priceList: pathSchema("Price list artifact path."),
        emitIntermediates: booleanSchema("Persist non-canonical sidecar artifacts."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "warden", repeatable: true },
      { key: "goal" },
      { key: "dungeonAffinity", flag: "dungeon-affinity" },
      { key: "budgetTokens", flag: "budget-tokens" },
      { key: "budget" },
      { key: "priceList", flag: "price-list" },
      { key: "emitIntermediates", flag: "emit-intermediates", boolean: true },
      { key: "outDir", flag: "out-dir" },
      { key: "runId", flag: "run-id" },
      { key: "createdAt", flag: "created-at" },
    ]),
  }),
];
