import {
  booleanSchema,
  buildArgv,
  createTool,
  DEFAULT_IPFS_GATEWAY,
  pathSchema,
  stringArraySchema,
  stringSchema,
  withCommonOutput,
} from "./shared.mjs";

export const externalTools = [
  createTool({
    name: "ak_ipfs",
    description: "Fetch IPFS content through the CLI adapter.",
    command: "ipfs",
    inputSchema: {
      required: ["cid"],
      properties: withCommonOutput({
        cid: stringSchema("Content identifier."),
        path: stringSchema("Path within the CID root."),
        gateway: stringSchema("IPFS gateway URL.", { default: DEFAULT_IPFS_GATEWAY }),
        json: booleanSchema("Write and return JSON output."),
        fixture: pathSchema("Fixture response path."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "cid" },
      { key: "path" },
      { key: "gateway", defaultValue: DEFAULT_IPFS_GATEWAY },
      { key: "json", boolean: true },
      { key: "fixture" },
      { key: "out" },
      { key: "outDir", flag: "out-dir" },
    ]),
  }),
  createTool({
    name: "ak_ipfs_publish",
    description: "Publish artifact maps through the IPFS adapter.",
    command: "ipfs-publish",
    inputSchema: {
      required: ["artifactMap"],
      properties: withCommonOutput({
        artifactMap: pathSchema("Artifact map JSON path."),
        path: stringSchema("Root path under the CID."),
        gateway: stringSchema("IPFS gateway URL.", { default: DEFAULT_IPFS_GATEWAY }),
        fixtureCid: stringSchema("Deterministic fixture CID."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "artifactMap", flag: "artifact-map" },
      { key: "path" },
      { key: "gateway", defaultValue: DEFAULT_IPFS_GATEWAY },
      { key: "fixtureCid", flag: "fixture-cid" },
      { key: "out" },
      { key: "outDir", flag: "out-dir" },
    ]),
  }),
  createTool({
    name: "ak_ipfs_load",
    description: "Load artifact files from IPFS through the CLI adapter.",
    command: "ipfs-load",
    inputSchema: {
      required: ["cid"],
      properties: withCommonOutput({
        cid: stringSchema("Content identifier."),
        path: stringSchema("Root path under the CID."),
        file: stringArraySchema("Specific files to load."),
        gateway: stringSchema("IPFS gateway URL.", { default: DEFAULT_IPFS_GATEWAY }),
        fixtureMap: pathSchema("Fixture JSON map path."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "cid" },
      { key: "path" },
      { key: "file", repeatable: true },
      { key: "gateway", defaultValue: DEFAULT_IPFS_GATEWAY },
      { key: "fixtureMap", flag: "fixture-map" },
      { key: "out" },
      { key: "outDir", flag: "out-dir" },
    ]),
  }),
  createTool({
    name: "ak_blockchain",
    description: "Inspect blockchain adapter state.",
    command: "blockchain",
    inputSchema: {
      required: ["rpcUrl"],
      properties: withCommonOutput({
        rpcUrl: stringSchema("JSON-RPC URL."),
        address: stringSchema("Address to inspect."),
        fixtureChainId: pathSchema("Fixture chain id response."),
        fixtureBalance: pathSchema("Fixture balance response."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "rpcUrl", flag: "rpc-url" },
      { key: "address" },
      { key: "fixtureChainId", flag: "fixture-chain-id" },
      { key: "fixtureBalance", flag: "fixture-balance" },
      { key: "out" },
      { key: "outDir", flag: "out-dir" },
    ]),
  }),
  createTool({
    name: "ak_blockchain_mint",
    description: "Mint a card through the blockchain adapter.",
    command: "blockchain-mint",
    inputSchema: {
      required: ["rpcUrl", "card"],
      properties: withCommonOutput({
        rpcUrl: stringSchema("JSON-RPC URL."),
        card: pathSchema("Card JSON path."),
        owner: stringSchema("Owner address."),
        contract: stringSchema("Contract address or alias."),
        tokenId: stringSchema("Token identifier."),
        fixtureChainId: pathSchema("Fixture chain id response."),
        fixtureMint: pathSchema("Fixture mint response."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "rpcUrl", flag: "rpc-url" },
      { key: "card" },
      { key: "owner" },
      { key: "contract" },
      { key: "tokenId", flag: "token-id" },
      { key: "fixtureChainId", flag: "fixture-chain-id" },
      { key: "fixtureMint", flag: "fixture-mint" },
      { key: "out" },
      { key: "outDir", flag: "out-dir" },
    ]),
  }),
  createTool({
    name: "ak_blockchain_load",
    description: "Load a minted card through the blockchain adapter.",
    command: "blockchain-load",
    inputSchema: {
      required: ["rpcUrl", "tokenId"],
      properties: withCommonOutput({
        rpcUrl: stringSchema("JSON-RPC URL."),
        tokenId: stringSchema("Token identifier."),
        owner: stringSchema("Owner address."),
        contract: stringSchema("Contract address or alias."),
        fixtureChainId: pathSchema("Fixture chain id response."),
        fixtureLoad: pathSchema("Fixture load response."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "rpcUrl", flag: "rpc-url" },
      { key: "tokenId", flag: "token-id" },
      { key: "owner" },
      { key: "contract" },
      { key: "fixtureChainId", flag: "fixture-chain-id" },
      { key: "fixtureLoad", flag: "fixture-load" },
      { key: "out" },
      { key: "outDir", flag: "out-dir" },
    ]),
  }),
];
