import {
  booleanSchema,
  buildArgv,
  createTool,
  integerSchema,
  pathSchema,
  stringArraySchema,
  stringSchema,
  withCommonOutput,
} from "./shared.mjs";

export const simulationTools = [
  createTool({
    name: "ak_build",
    description: "Build artifacts from a build spec.",
    command: "build",
    inputSchema: {
      required: ["spec"],
      properties: withCommonOutput({
        spec: pathSchema("Build spec JSON path."),
        emitIntermediates: booleanSchema("Persist non-canonical sidecar artifacts."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "spec" },
      { key: "emitIntermediates", flag: "emit-intermediates", boolean: true },
      { key: "outDir", flag: "out-dir" },
    ]),
  }),
  createTool({
    name: "ak_solve",
    description: "Solve a scenario into runnable artifacts.",
    command: "solve",
    inputSchema: {
      required: ["scenario"],
      properties: withCommonOutput({
        scenario: stringSchema("Scenario text."),
        plan: pathSchema("Existing plan artifact path."),
        intent: pathSchema("Existing intent artifact path."),
        options: pathSchema("Solve options path."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "scenario" },
      { key: "plan" },
      { key: "intent" },
      { key: "options" },
      { key: "outDir", flag: "out-dir" },
      { key: "runId", flag: "run-id" },
    ]),
  }),
  createTool({
    name: "ak_run",
    description: "Run a simulation from artifacts or from an existing run.",
    command: "run",
    inputSchema: {
      properties: withCommonOutput({
        simConfig: pathSchema("Sim config artifact path."),
        initialState: pathSchema("Initial state artifact path."),
        fromRun: stringSchema("Existing run id to resolve sim-config and initial-state from."),
        executionPolicy: pathSchema("Execution policy path."),
        ticks: integerSchema("Tick count.", { minimum: 1 }),
        seed: integerSchema("Initialization seed.", { minimum: 0 }),
        actor: stringArraySchema("Actor override specs."),
        vital: stringArraySchema("Vital override specs."),
        vitalDefault: stringArraySchema("Default vital specs."),
        tileWall: stringArraySchema("Wall tile coordinates."),
        tileBarrier: stringArraySchema("Barrier tile coordinates."),
        tileFloor: stringArraySchema("Floor tile overrides."),
        actions: pathSchema("ActionSequence path."),
        affinityPresets: pathSchema("AffinityPresetArtifact path."),
        affinityLoadouts: pathSchema("ActorLoadoutArtifact path."),
        affinitySummary: pathSchema("Affinity summary output path."),
        progress: booleanSchema("Emit tick progress events."),
        dryRun: booleanSchema("Validate resolved inputs without executing."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "simConfig", flag: "sim-config" },
      { key: "initialState", flag: "initial-state" },
      { key: "fromRun", flag: "from-run" },
      { key: "executionPolicy", flag: "execution-policy" },
      { key: "ticks" },
      { key: "seed" },
      { key: "outDir", flag: "out-dir" },
      { key: "runId", flag: "run-id" },
      { key: "actor", repeatable: true },
      { key: "vital", repeatable: true },
      { key: "vitalDefault", flag: "vital-default", repeatable: true },
      { key: "tileWall", flag: "tile-wall", repeatable: true },
      { key: "tileBarrier", flag: "tile-barrier", repeatable: true },
      { key: "tileFloor", flag: "tile-floor", repeatable: true },
      { key: "actions" },
      { key: "affinityPresets", flag: "affinity-presets" },
      { key: "affinityLoadouts", flag: "affinity-loadouts" },
      { key: "affinitySummary", flag: "affinity-summary" },
      { key: "progress", boolean: true },
      { key: "dryRun", flag: "dry-run", boolean: true },
    ]),
  }),
  createTool({
    name: "ak_configurator",
    description: "Assemble simulation config and initial state inputs.",
    command: "configurator",
    inputSchema: {
      required: ["levelGen", "actors"],
      properties: withCommonOutput({
        levelGen: pathSchema("Level generation input path."),
        actors: pathSchema("Actors input path."),
        plan: pathSchema("Plan artifact path."),
        budgetReceipt: pathSchema("Budget receipt artifact path."),
        budget: pathSchema("Budget artifact path."),
        priceList: pathSchema("Price list artifact path."),
        receiptOut: pathSchema("Output path for budget receipt."),
        affinityPresets: pathSchema("Affinity preset artifact path."),
        affinityLoadouts: pathSchema("Actor loadout artifact path."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "levelGen", flag: "level-gen" },
      { key: "actors" },
      { key: "plan" },
      { key: "budgetReceipt", flag: "budget-receipt" },
      { key: "budget" },
      { key: "priceList", flag: "price-list" },
      { key: "receiptOut", flag: "receipt-out" },
      { key: "affinityPresets", flag: "affinity-presets" },
      { key: "affinityLoadouts", flag: "affinity-loadouts" },
      { key: "outDir", flag: "out-dir" },
      { key: "runId", flag: "run-id" },
    ]),
  }),
  createTool({
    name: "ak_budget",
    description: "Compute a budget receipt from budget and price list artifacts.",
    command: "budget",
    inputSchema: {
      required: ["budget"],
      properties: withCommonOutput({
        budget: pathSchema("Budget artifact path."),
        priceList: pathSchema("Price list artifact path."),
        receipt: pathSchema("Budget receipt artifact path."),
        receiptOut: pathSchema("Output path for budget receipt JSON."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "budget" },
      { key: "priceList", flag: "price-list" },
      { key: "receipt" },
      { key: "outDir", flag: "out-dir" },
      { key: "out" },
      { key: "receiptOut", flag: "receipt-out" },
    ]),
  }),
  createTool({
    name: "ak_replay",
    description: "Replay a run deterministically from recorded tick frames.",
    command: "replay",
    inputSchema: {
      required: ["simConfig", "initialState", "tickFrames"],
      properties: withCommonOutput({
        simConfig: pathSchema("Sim config artifact path."),
        initialState: pathSchema("Initial state artifact path."),
        tickFrames: pathSchema("Tick frames path."),
        executionPolicy: pathSchema("Execution policy path."),
        ticks: integerSchema("Tick count.", { minimum: 1 }),
        seed: integerSchema("Initialization seed.", { minimum: 0 }),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "simConfig", flag: "sim-config" },
      { key: "initialState", flag: "initial-state" },
      { key: "tickFrames", flag: "tick-frames" },
      { key: "executionPolicy", flag: "execution-policy" },
      { key: "ticks" },
      { key: "seed" },
      { key: "outDir", flag: "out-dir" },
    ]),
  }),
  createTool({
    name: "ak_scenario",
    description: "Run llm-plan plus run plus inspect as a single scenario pipeline.",
    command: "scenario",
    inputSchema: {
      properties: withCommonOutput({
        text: stringSchema("Scenario text input."),
        fromRun: stringSchema("Existing run id to reuse artifacts from."),
        catalog: pathSchema("Catalog path for text-driven llm-plan."),
        model: stringSchema("LLM model override."),
        goal: stringSchema("Goal override."),
        budgetTokens: integerSchema("Hard budget cap in tokens.", { minimum: 1 }),
        baseUrl: stringSchema("LLM base URL."),
        fixture: pathSchema("LLM fixture path."),
        budgetLoop: booleanSchema("Enable llm-plan budget loop."),
        budgetPool: stringArraySchema("Budget pool weights in id=weight form."),
        budgetReserve: integerSchema("Budget reserve before pooling.", { minimum: 0 }),
        ticks: integerSchema("Tick count.", { minimum: 1 }),
        seed: integerSchema("Initialization seed.", { minimum: 0 }),
        emitIntermediates: booleanSchema("Persist non-canonical llm-plan sidecar artifacts."),
        dryRun: booleanSchema("Validate scenario inputs without executing."),
      }),
    },
    buildArgs: (args) => buildArgv(args, [
      { key: "text" },
      { key: "fromRun", flag: "from-run" },
      { key: "catalog" },
      { key: "model" },
      { key: "goal" },
      { key: "budgetTokens", flag: "budget-tokens" },
      { key: "baseUrl", flag: "base-url" },
      { key: "fixture" },
      { key: "budgetLoop", flag: "budget-loop", boolean: true },
      { key: "budgetPool", flag: "budget-pool", repeatable: true },
      { key: "budgetReserve", flag: "budget-reserve" },
      { key: "emitIntermediates", flag: "emit-intermediates", boolean: true },
      { key: "ticks" },
      { key: "seed" },
      { key: "outDir", flag: "out-dir" },
      { key: "runId", flag: "run-id" },
      { key: "createdAt", flag: "created-at" },
      { key: "dryRun", flag: "dry-run", boolean: true },
    ]),
  }),
];
