const { existsSync } = require("node:fs");
const { readFile } = require("node:fs/promises");
const { resolve } = require("node:path");

async function loadCoreFromWasmPath(wasmPath) {
  const buffer = await readFile(wasmPath);
  const { instance } = await WebAssembly.instantiate(buffer, {
    env: {
      abort(_msg, _file, line, column) {
        throw new Error(`WASM abort at ${line}:${column}`);
      },
    },
  });
  const exports = instance.exports;
  return {
    init: exports.init,
    step: exports.step,
    applyAction: exports.applyAction,
    setMoveAction: exports.setMoveAction,
    getCounter: exports.getCounter,
    setBudget: exports.setBudget,
    getBudget: exports.getBudget,
    getBudgetUsage: exports.getBudgetUsage,
    getEffectCount: exports.getEffectCount,
    getEffectKind: exports.getEffectKind,
    getEffectValue: exports.getEffectValue,
    getEffectActorId: exports.getEffectActorId,
    getEffectX: exports.getEffectX,
    getEffectY: exports.getEffectY,
    getEffectReason: exports.getEffectReason,
    getEffectDelta: exports.getEffectDelta,
    clearEffects: exports.clearEffects,
    version: exports.version,
    loadMvpScenario: exports.loadMvpScenario,
    loadMvpBarrierScenario: exports.loadMvpBarrierScenario,
    configureGrid: exports.configureGrid,
    prepareTileBuffer: exports.prepareTileBuffer,
    loadTilesFromBuffer: exports.loadTilesFromBuffer,
    memory: exports.memory,
    setTileAt: exports.setTileAt,
    spawnActorAt: exports.spawnActorAt,
    setSpawnPosition: exports.setSpawnPosition,
    clearActorPlacements: exports.clearActorPlacements,
    addActorPlacement: exports.addActorPlacement,
    getActorPlacementCount: exports.getActorPlacementCount,
    validateActorPlacement: exports.validateActorPlacement,
    applyActorPlacements: exports.applyActorPlacements,
    setMotivatedActorVital: exports.setMotivatedActorVital,
    setMotivatedActorMovementCost: exports.setMotivatedActorMovementCost,
    setMotivatedActorActionCostMana: exports.setMotivatedActorActionCostMana,
    setMotivatedActorActionCostStamina: exports.setMotivatedActorActionCostStamina,
    getMapWidth: exports.getMapWidth,
    getMapHeight: exports.getMapHeight,
    getActorId: exports.getActorId,
    getActorX: exports.getActorX,
    getActorY: exports.getActorY,
    getActorKind: exports.getActorKind,
    getTileActorKind: exports.getTileActorKind,
    getTileActorId: exports.getTileActorId,
    getTileActorCount: exports.getTileActorCount,
    getTileActorIndex: exports.getTileActorIndex,
    getTileActorXByIndex: exports.getTileActorXByIndex,
    getTileActorYByIndex: exports.getTileActorYByIndex,
    getTileActorKindByIndex: exports.getTileActorKindByIndex,
    getTileActorIdByIndex: exports.getTileActorIdByIndex,
    getTileActorDurabilityByIndex: exports.getTileActorDurabilityByIndex,
    getTileActorDurability: exports.getTileActorDurability,
    raiseBarrierAt: exports.raiseBarrierAt,
    destroyBarrierAt: exports.destroyBarrierAt,
    armStaticTrapAt: exports.armStaticTrapAt,
    disarmStaticTrapAt: exports.disarmStaticTrapAt,
    getStaticTrapCount: exports.getStaticTrapCount,
    getStaticTrapAffinityAt: exports.getStaticTrapAffinityAt,
    getStaticTrapExpressionAt: exports.getStaticTrapExpressionAt,
    getStaticTrapStacksAt: exports.getStaticTrapStacksAt,
    getStaticTrapManaReserveAt: exports.getStaticTrapManaReserveAt,
    getActorVitalCurrent: exports.getActorVitalCurrent,
    getActorVitalMax: exports.getActorVitalMax,
    getActorVitalRegen: exports.getActorVitalRegen,
    getActorMovementCost: exports.getActorMovementCost,
    getActorActionCostMana: exports.getActorActionCostMana,
    getActorActionCostStamina: exports.getActorActionCostStamina,
    setActorVital: exports.setActorVital,
    setActorMovementCost: exports.setActorMovementCost,
    setActorActionCostMana: exports.setActorActionCostMana,
    setActorActionCostStamina: exports.setActorActionCostStamina,
    validateActorVitals: exports.validateActorVitals,
    validateActorCapabilities: exports.validateActorCapabilities,
    getMotivatedActorCount: exports.getMotivatedActorCount,
    getMotivatedActorIdByIndex: exports.getMotivatedActorIdByIndex,
    getMotivatedActorXByIndex: exports.getMotivatedActorXByIndex,
    getMotivatedActorYByIndex: exports.getMotivatedActorYByIndex,
    getMotivatedActorVitalCurrentByIndex: exports.getMotivatedActorVitalCurrentByIndex,
    getMotivatedActorVitalMaxByIndex: exports.getMotivatedActorVitalMaxByIndex,
    getMotivatedActorVitalRegenByIndex: exports.getMotivatedActorVitalRegenByIndex,
    getMotivatedActorMovementCostByIndex: exports.getMotivatedActorMovementCostByIndex,
    getMotivatedActorActionCostManaByIndex: exports.getMotivatedActorActionCostManaByIndex,
    getMotivatedActorActionCostStaminaByIndex: exports.getMotivatedActorActionCostStaminaByIndex,
    getCurrentTick: exports.getCurrentTick,
    advanceTick: exports.advanceTick,
    renderCellChar: exports.renderCellChar,
    renderBaseCellChar: exports.renderBaseCellChar,
    placeResourceAt: exports.placeResourceAt,
    removeResourceAt: exports.removeResourceAt,
    hasResourceAt: exports.hasResourceAt,
    getResourceVitalKindAt: exports.getResourceVitalKindAt,
    getResourceDeltaAt: exports.getResourceDeltaAt,
    getResourceModeAt: exports.getResourceModeAt,
    getResourceCount: exports.getResourceCount,
    // Affinity codebook
    getAffinityKindCount: exports.getAffinityKindCount,
    getAffinityExpressionCount: exports.getAffinityExpressionCount,
    getAffinityTargetTypeCount: exports.getAffinityTargetTypeCount,
    getOppositeAffinityKind: exports.getOppositeAffinityKind,
    resolveAffinityRelationshipCode: exports.resolveAffinityRelationshipCode,
    getAffinityTargetVital: exports.getAffinityTargetVital,
    getDefaultAffinityTargetType: exports.getDefaultAffinityTargetType,
    affinityExpressionAllowsEnvironmentMutation: exports.affinityExpressionAllowsEnvironmentMutation,
    affinityExpressionAllowsTrapArming: exports.affinityExpressionAllowsTrapArming,
    affinityExpressionIsPersistentField: exports.affinityExpressionIsPersistentField,
    // Motivation codebook
    getMotivationKindCount: exports.getMotivationKindCount,
    getMotivationFamily: exports.getMotivationFamily,
    getMotivationExclusiveGroup: exports.getMotivationExclusiveGroup,
    motivationKindsConflict: exports.motivationKindsConflict,
    getMotivationPatternCount: exports.getMotivationPatternCount,
    getMotivationPatternCodeAt: exports.getMotivationPatternCodeAt,
    getDefaultMotivationPattern: exports.getDefaultMotivationPattern,
    // Motivation validation + cost
    normalizeMotivationIntensity: exports.normalizeMotivationIntensity,
    getMotivationTier: exports.getMotivationTier,
    getMotivationDefaultUnitCost: exports.getMotivationDefaultUnitCost,
    resetMotivationCostAccumulator: exports.resetMotivationCostAccumulator,
    addMotivationCostEntry: exports.addMotivationCostEntry,
    getMotivationCostTotal: exports.getMotivationCostTotal,
    getMotivationCostLineCount: exports.getMotivationCostLineCount,
    getMotivationCostLineKind: exports.getMotivationCostLineKind,
    getMotivationCostLineFamily: exports.getMotivationCostLineFamily,
    getMotivationCostLineQuantity: exports.getMotivationCostLineQuantity,
    getMotivationCostLineUnitCost: exports.getMotivationCostLineUnitCost,
    getMotivationCostLineSpend: exports.getMotivationCostLineSpend,
    // Motivation behavior flags + evaluation
    getMotivationFlagCount: exports.getMotivationFlagCount,
    getMotivationProfileCost: exports.getMotivationProfileCost,
    getMotivationDefaultDesignCost: exports.getMotivationDefaultDesignCost,
    getMotivationDefaultFlagMask: exports.getMotivationDefaultFlagMask,
    resetMotivationEvaluation: exports.resetMotivationEvaluation,
    addMotivationEvaluationEntry: exports.addMotivationEvaluationEntry,
    evaluateMotivations: exports.evaluateMotivations,
    getLastMotivationFlags: exports.getLastMotivationFlags,
    getLastMotivationMobilityTier: exports.getLastMotivationMobilityTier,
    getLastMotivationCombatTier: exports.getLastMotivationCombatTier,
    getLastMotivationCognitionTier: exports.getLastMotivationCognitionTier,
    getLastMotivationReasoningClass: exports.getLastMotivationReasoningClass,
    // Affinity spatial formulas
    computeAffinityRadius: exports.computeAffinityRadius,
    computeAffinityIntensity: exports.computeAffinityIntensity,
    computeAffinityPotency: exports.computeAffinityPotency,
    computeAffinityManaCost: exports.computeAffinityManaCost,
    resolveAffinityStackCancellation: exports.resolveAffinityStackCancellation,
    getLastAffinityCanceledStacks: exports.getLastAffinityCanceledStacks,
    getLastAffinityNetSourceStacks: exports.getLastAffinityNetSourceStacks,
    getLastAffinityNetTargetStacks: exports.getLastAffinityNetTargetStacks,
    resolveAffinityMergedStacks: exports.resolveAffinityMergedStacks,
    // Affinity interaction matrix
    getAffinityInteractionCellCount: exports.getAffinityInteractionCellCount,
    getAffinityVisualStateCount: exports.getAffinityVisualStateCount,
    getAffinityEffectCount: exports.getAffinityEffectCount,
    getAffinityMatrixSourceEffect: exports.getAffinityMatrixSourceEffect,
    getAffinityMatrixTargetEffect: exports.getAffinityMatrixTargetEffect,
    getAffinityMatrixVisualState: exports.getAffinityMatrixVisualState,
    getAffinityMatrixUsesStackCancellation: exports.getAffinityMatrixUsesStackCancellation,
    // Affinity field buffers
    clearAffinityField: exports.clearAffinityField,
    computeStaticTrapAffinityField: exports.computeStaticTrapAffinityField,
    getAffinityFieldIntensityAt: exports.getAffinityFieldIntensityAt,
    getAffinityFieldStacksAt: exports.getAffinityFieldStacksAt,
    getAffinityFieldExpressionAt: exports.getAffinityFieldExpressionAt,
    getAffinityFieldContributionCountAt: exports.getAffinityFieldContributionCountAt,
    // Actor affinity state + fields
    setMotivatedActorAffinity: exports.setMotivatedActorAffinity,
    getMotivatedActorAffinityKindByIndex: exports.getMotivatedActorAffinityKindByIndex,
    getMotivatedActorAffinityExpressionByIndex: exports.getMotivatedActorAffinityExpressionByIndex,
    getMotivatedActorAffinityStacksByIndex: exports.getMotivatedActorAffinityStacksByIndex,
    computeActorAffinityField: exports.computeActorAffinityField,
    computeAffinityField: exports.computeAffinityField,
    // Affinity interaction resolution
    resolveAffinityInteraction: exports.resolveAffinityInteraction,
    resolveMotivatedActorAffinityInteraction: exports.resolveMotivatedActorAffinityInteraction,
    getLastInteractionSourceEffect: exports.getLastInteractionSourceEffect,
    getLastInteractionTargetEffect: exports.getLastInteractionTargetEffect,
    getLastInteractionVisualState: exports.getLastInteractionVisualState,
    getLastInteractionRelationship: exports.getLastInteractionRelationship,
    getLastInteractionNetSourceStacks: exports.getLastInteractionNetSourceStacks,
    getLastInteractionNetTargetStacks: exports.getLastInteractionNetTargetStacks,
    getLastInteractionCanceledStacks: exports.getLastInteractionCanceledStacks,
  };
}

function resolveWasmPath(relativePath = "build/core-as.wasm") {
  return resolve(process.cwd(), relativePath);
}

function resolveWasmPathOrThrow(relativePath = "build/core-as.wasm") {
  const wasmPath = resolveWasmPath(relativePath);
  if (!existsSync(wasmPath)) {
    throw new Error(`WASM not found at ${wasmPath}`);
  }
  return wasmPath;
}

module.exports = {
  loadCoreFromWasmPath,
  resolveWasmPath,
  resolveWasmPathOrThrow,
};
